import numpy as np
import scanpy as sc
import os
import pickle

import lognorm_workflow_analytic as lwa
import analysis_spike_util as asu
import nb_model
import datasets
import datasets_celltype


# cell-type spike pkls are built from ../analysis_HVG_celltype/ (see
# datasets_celltype.py) rather than ../analysis_HVG/ or
# ../analysis_HVG_refined/ -- there is no refined/unrefined split here, since
# a cell-type metacell is not something refinement operates on
SPIKE_CELLTYPE_DIR = "../analysis_spike_celltype/"

# normal/nb/perm/true come from a genuine SVD of an (n_cells x n_genes)
# matrix, and so have right singular vectors. `analytic` is deliberately not
# among them: it is the reference the others are compared against, and its
# spec_analytic is built from pca_theory rather than decomposed.
#
# <base>_proj_i are simulated rather than decomposed: the analytic model's
# metacell moments projected onto that base method's basis, with a rank-i PSD
# correction fitted against the base's own empirical covariances, then sampled
# one cell per row (see anndata2spike_celltype). perm is the permutation null
# and true is the real data, so the two series show how much of each basis's
# covariance structure the model plus i correction directions reproduces.
# They carry no V -- there is no gene-space decomposition behind them -- so
# they can be consumed anywhere a spec's U*sv scores are used, but cannot
# serve as a projection basis.
PROJ_RANKS = [0, 1, 2, 3]
PROJ_BASES = ["perm", "true"]
PROJ_METHODS = [f"{base}_proj_{i}" for base in PROJ_BASES for i in PROJ_RANKS]
SPIKE_METHODS = ["normal", "nb", "perm", "true"] + PROJ_METHODS
SPEC_KEYS = {"normal": "spec_n", "nb": "spec_nb",
             "perm": "spec_perm", "true": "spec_true"}
SPEC_KEYS.update({m: f"spec_{m}" for m in PROJ_METHODS})


##############################################################
# functions to create the pkl objects with the analytic PCA
# and the different empirical PCAs generated by different log-normalized count
# matrices, for the cell-type-as-metacell HVG datasets (datasets_celltype.py):
#  normal:  spike + gaussian noise
#  nb:  counts generated by a nb, then log-normalized + PCA
#  perm:  counts permuted within cell types, then log-normalized + PCA
#  true:  true counts, then log-normalized + PCA
#  analytic:  the model's own predicted PCA (the reference)


def permute_genes_within_celltype(X, cell_types):
    cell_types = np.asarray(cell_types)
    n_genes = X.shape[1]
    X = np.asarray(X)

    permuted = np.empty_like(X)
    for ct in np.unique(cell_types):
        idx = np.where(cell_types == ct)[0]
        n_ct = len(idx)

        block = X[idx, :]

        # independent random permutation of rows for each gene column
        perm_idx = np.argsort(np.random.rand(n_ct, n_genes), axis=0)
        permuted[idx, :] = np.take_along_axis(block, perm_idx, axis=0)

    return permuted


def simulate_projected_specs(pca_theory, spec_base, cell_labels, base_name):
    """The four spec_<base_name>_proj_i specs, one per rank in PROJ_RANKS.

    The analytic model's per-metacell moments are carried onto spec_base's
    basis (analysis_spike_util.compute_spike_projection), corrected toward
    spec_base's own empirical covariances by the best PSD rank-i term
    (rank_adjust_spike_projection), and sampled one cell per row of
    cell_labels (simulate_spike_projection). Rank 0 is the uncorrected
    projection, so the series shows what each extra correction rank buys.

    Each rank starts from a fresh copy of the unadjusted projection, so rank i
    is fitted from scratch rather than on top of rank i-1's correction
    (rank_adjust_spike_projection does not mutate its argument, but the copy
    makes that independence explicit).

    Every spec is {'sv': column norms of Y, 'U': Y with unit-norm columns,
    'V': None}, so U*sv == Y exactly and sv means what it does for the
    SVD-derived specs -- their U is orthonormal, so their sv_j is likewise
    ||Y[:, j]||. Unlike those, these columns are not orthogonal to one
    another, and there is no V because nothing was decomposed.
    """
    sp = asu.compute_spike_projection(pca_theory, spec_base, cell_labels)

    specs = {}
    for i in PROJ_RANKS:
        sp_i = {key: np.array(value, copy=True) for key, value in sp.items()}
        sp_i = asu.rank_adjust_spike_projection(sp_i, spec_base, cell_labels,
                                                rank_adjust=i)
        Y_i = asu.simulate_spike_projection(sp_i, cell_labels)
        sv_i = np.linalg.norm(Y_i, axis=0)
        U_i = np.divide(Y_i, sv_i, out=np.zeros_like(Y_i), where=sv_i > 0)
        specs[f"spec_{base_name}_proj_{i}"] = {'sv': sv_i, 'U': U_i, 'V': None}
    return specs


def reorder_rows_to_match_labels(U, source_labels, target_labels):
    """Permute the rows of `U` (each currently tagged by source_labels) so
    that row i instead corresponds to target_labels[i], one to one.

    `source_labels` and `target_labels` must contain the same labels with the
    same per-label counts (only the row order differs) -- rows sharing a
    label are exchangeable, so any 1-to-1 pairing between the two orderings
    is valid.
    """
    source_labels = np.asarray(source_labels)
    target_labels = np.asarray(target_labels)
    if len(source_labels) != len(target_labels):
        raise ValueError("source_labels and target_labels must have the same length")

    perm = np.empty(len(target_labels), dtype=int)
    for label in np.unique(target_labels):
        source_idx = np.where(source_labels == label)[0]
        target_idx = np.where(target_labels == label)[0]
        if len(source_idx) != len(target_idx):
            raise ValueError(f"label '{label}' has {len(source_idx)} rows in source_labels "
                             f"but {len(target_idx)} rows in target_labels")
        perm[target_idx] = source_idx

    return U[perm]


def get_spike_celltype_filename(dataset, n_genes):
    """Path of the spec pkl, creating the folder if it does not exist.

    Holds the spec_* dicts only; the analytic PCA it was built from lives
    alongside it under get_pca_celltype_filename.
    """
    os.makedirs(SPIKE_CELLTYPE_DIR, exist_ok=True)
    return os.path.join(SPIKE_CELLTYPE_DIR, f"{dataset}_HVG_{n_genes}.pkl")


def get_pca_celltype_filename(dataset, n_genes):
    """Path of the analytic-PCA pkl, creating the folder if it does not exist.

    Split out from the spec pkl because log_normalized_PCA dominates the cost
    of anndata2spike_celltype -- 69-80% of its runtime, growing with k^2 --
    while the spec_* dicts around it take seconds. Keeping them apart means a
    new spec method can be added without paying for the analytic PCA again.
    """
    os.makedirs(SPIKE_CELLTYPE_DIR, exist_ok=True)
    return os.path.join(SPIKE_CELLTYPE_DIR, f"{dataset}_HVG_{n_genes}_pca.pkl")


def has_spike_celltype_result(dataset, n_genes):
    """True when both halves of the split result are on disk. Consumers want
    the merged dict, so either half alone is not usable."""
    return (os.path.isfile(get_pca_celltype_filename(dataset, n_genes))
            and os.path.isfile(get_spike_celltype_filename(dataset, n_genes)))


def load_spike_celltype_result(dataset, n_genes):
    """Both halves merged into one dict: the spec_* entries plus "pca_theory".

    Every consumer wants the two together, so the split is an on-disk detail
    that stops here rather than propagating outwards.
    """
    pca_f = get_pca_celltype_filename(dataset, n_genes)
    spec_f = get_spike_celltype_filename(dataset, n_genes)
    for f in (pca_f, spec_f):
        if not os.path.isfile(f):
            raise FileNotFoundError(
                f"{f} not found; build it with "
                f"anndata2spike_celltype('{dataset}', {n_genes})")
    with open(spec_f, "rb") as f:
        result = pickle.load(f)
    with open(pca_f, "rb") as f:
        result["pca_theory"] = pickle.load(f)
    return result


def anndata2spike_celltype(dataset, n_genes, overwrite=False):
    """Build (or load) the analytic PCA and the spec_* dicts, cached as two
    pkls under get_pca_celltype_filename and get_spike_celltype_filename, for
    the cell-type-as-metacell HVG dataset (datasets_celltype.py).

    One `overwrite` flag covers both, but the halves are not independent:

        overwrite    pca pkl   spec pkl   action
        True         -         -          recompute both
        False        missing   either     recompute both
        False        exists    missing    load the pca, recompute the specs
        False        exists    exists     load both

    Row 3 is the point of the split -- log_normalized_PCA dominates the cost,
    so adding a spec method costs seconds rather than minutes. Row 2 rebuilds
    the specs even when they are present, because spec_analytic is derived from
    pca_theory: pairing an old spec pkl with a freshly computed PCA would
    silently mix two different k and two different eigenbases.

    Every spec carries "U", "sv" and "V". U's rows follow the h5ad's cell order
    for ALL specs including spec_analytic, which is realigned here out of
    pca_theory's own sample_labels order -- so the specs are row-comparable to
    one another, while pca_theory itself keeps its original ordering.

    "cell_labels" is stored alongside the specs: the h5ad's metacell column
    (here, exactly the cell type -- see datasets_celltype.py), one entry per
    row, in the specs' own row order.

    V holds the right singular vectors (gene loadings), p x k. For nb/perm/true
    /normal it is the SVD's own V; spec_analytic has no SVD behind it, so it
    carries pca_theory's mean_gene_matrix, the model's predicted gene loading
    per PC. Note that one is NOT orthonormal (column norms ~0.97-1.00, Gram
    off-diagonals up to 0.008), unlike the four empirical V's.
    """
    pca_f = get_pca_celltype_filename(dataset, n_genes)
    spec_f = get_spike_celltype_filename(dataset, n_genes)
    have_pca = os.path.isfile(pca_f) and not overwrite

    if have_pca and os.path.isfile(spec_f):
        result = load_spike_celltype_result(dataset, n_genes)
        # a pkl written before perm_proj existed simply lacks those keys; they
        # come back as None rather than raising, so old caches stay readable
        # until they are rebuilt with overwrite=True
        return (result["pca_theory"], result["spec_analytic"], result["spec_nb"],
                result["spec_perm"], result["spec_true"], result["spec_n"],
                *(result.get(SPEC_KEYS[m]) for m in PROJ_METHODS))

    s = datasets_celltype.load_HVG_celltype_dataset(dataset, n_genes)
    n = s.n_obs
    nb = s.uns["nb_model"]

    if have_pca:
        print(f"Loading the cached analytic PCA from {os.path.basename(pca_f)}")
        with open(pca_f, "rb") as f:
            pca_theory = pickle.load(f)
    else:
        pca_theory = lwa.log_normalized_PCA(nb, s.n_obs)
        with open(pca_f, "wb") as f:
            pickle.dump(pca_theory, f)

    cell_labels = s.obs["metacell"].to_numpy()

    # each metacell's cells are drawn at that metacell's own nb["L"][i], the
    # same per-metacell L pca_theory and spec_n are built at (as in
    # analysis_spike.anndata2spike)
    print("Simulating the NB data")
    X = nb_model.simulate_X(nb, cell_labels)
    s_nb = sc.AnnData(X)
    sc.pp.normalize_total(s_nb, target_sum=1e4)
    sc.pp.log1p(s_nb)
    sc.pp.scale(s_nb)
    U_nb, sv_nb, Vt_nb = np.linalg.svd(s_nb.X, full_matrices=False)

    print("Permuting the genes within cell types")
    X_true = s.X.toarray()
    X_true_permuted = permute_genes_within_celltype(X_true, cell_labels)
    s_perm = sc.AnnData(X_true_permuted)
    sc.pp.normalize_total(s_perm, target_sum=1e4)
    sc.pp.log1p(s_perm)
    sc.pp.scale(s_perm)
    U_perm, sv_perm, Vt_perm = np.linalg.svd(s_perm.X, full_matrices=False)

    print("Computing the PCA eigenvalues")
    s_new = s.copy()
    sc.pp.normalize_total(s_new, target_sum=1e4)
    sc.pp.log1p(s_new)
    sc.pp.scale(s_new)
    U_true, sv_true, Vt_true = np.linalg.svd(s_new.X, full_matrices=False)

    print("Compute Normal Noise Model")
    m_model, spike = lwa.log_normalized_spiked_mixture_model(nb, s.shape[0], include_spike=True)
    Z = lwa.simulate_Z_guassian(m_model, spike)
    U_n, sv_n, Vt_n = np.linalg.svd(Z, full_matrices=False)
    U_n = reorder_rows_to_match_labels(U_n, spike["sample_labels"], cell_labels)

    k = len(pca_theory["values"])
    # spec_analytic is realigned into the h5ad's cell order so every spec
    # shares one row order; pca_theory keeps its own sample_labels ordering.
    # Its V is the model's predicted gene loading rather than an SVD factor.
    U_analytic = reorder_rows_to_match_labels(
        pca_theory["vectors"][:, :k], pca_theory["sample_labels"], cell_labels)
    spec_analytic = {'sv': pca_theory["values"][:k], 'U': U_analytic,
                     'V': np.asarray(pca_theory["mean_gene_matrix"])[:, :k]}
    spec_nb = {'sv': sv_nb[:k]/np.sqrt(n), 'U': U_nb[:, :k], 'V': Vt_nb[:k, :].T}
    spec_perm = {'sv': sv_perm[:k]/np.sqrt(n), 'U': U_perm[:, :k], 'V': Vt_perm[:k, :].T}
    spec_true = {'sv': sv_true[:k]/np.sqrt(n), 'U': U_true[:, :k], 'V': Vt_true[:k, :].T}
    spec_n = {'sv': sv_n[:k], 'U': U_n[:, :k], 'V': Vt_n[:k, :].T}

    # one <base>_proj_i family per PROJ_BASES entry -- see
    # simulate_projected_specs for what they are
    spec_proj = {}
    base_specs = {"perm": spec_perm, "true": spec_true}
    for base_name in PROJ_BASES:
        print(f"Simulating the projected analytic specs against {base_name}")
        spec_proj.update(simulate_projected_specs(
            pca_theory, base_specs[base_name], cell_labels, base_name))

    # pca_theory is deliberately absent here -- it is the other pkl, and
    # load_spike_celltype_result puts the two back together
    # cell_labels rides along so consumers can group the spec rows by metacell
    # without reopening the h5ad. It CANNOT be recovered from pca_theory:
    # pca_theory["sample_labels"] describes that object's own row order, which
    # is contiguous metacell blocks, whereas the specs follow the h5ad's own
    # cell order.
    result = {"spec_analytic": spec_analytic, "spec_nb": spec_nb,
              "spec_perm": spec_perm, "spec_true": spec_true, "spec_n": spec_n,
              "cell_labels": cell_labels}
    result.update(spec_proj)
    with open(spec_f, "wb") as f:
        pickle.dump(result, f)

    return (pca_theory, spec_analytic, spec_nb, spec_perm, spec_true, spec_n,
            *(spec_proj[SPEC_KEYS[m]] for m in PROJ_METHODS))


def make_all_spike_pkl_celltype(datasets_list=datasets.DEFAULT_DATASETS,
                                n_genes_list=datasets.DEFAULT_N_GENES,
                                overwrite=False):
    for dataset in datasets_list:
        for n_genes in n_genes_list:
            print(f"Processing {dataset} HVG {n_genes}")
            try:
                anndata2spike_celltype(dataset, n_genes, overwrite=overwrite)
            except ValueError as e:
                # the HVG h5ad for this combination has not been built yet;
                # skip it rather than abandoning the rest of the sweep
                print(f"  SKIPPING {dataset}/{n_genes}: {e}")
    return None
