import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
from scipy.stats import norm
import os
import pickle

import lognorm_workflow_analytic as lwa
import analysis_spike_util as asu
import nb_model
import datasets
import datasets_refined as dr


# spike pkls are split by provenance the same way the HVG h5ads they are
# built from are: refined ones come from analysis_HVG_refined, unrefined
# from analysis_HVG
SPIKE_DIR = "../analysis_spike/"
SPIKE_REFINED_DIR = "../analysis_spike_refined/"

# normal/nb/perm/true come from a genuine SVD of an (n_cells x n_genes)
# matrix, and so have right singular vectors. `analytic` is deliberately not
# among them: it is the reference the others are compared against, and its
# spec_analytic is built from pca_theory rather than decomposed.
#
# <base>_proj_i are simulated rather than decomposed: the analytic model's
# metacell moments projected onto that base method's basis, with a rank-i PSD
# correction fitted against the base's own empirical covariances, then sampled
# one cell per row (see anndata2spike). perm is the permutation null and true
# is the real data, so the two series show how much of each basis's covariance
# structure the model plus i correction directions reproduces. They carry no V
# -- there is no gene-space decomposition behind them -- so they can be
# consumed anywhere a spec's U*sv scores are used, but cannot serve as a
# projection basis.
PROJ_RANKS = [0, 1, 2, 3]
PROJ_BASES = ["perm", "true"]
PROJ_METHODS = [f"{base}_proj_{i}" for base in PROJ_BASES for i in PROJ_RANKS]
SPIKE_METHODS = ["normal", "nb", "perm", "true"] + PROJ_METHODS
SPEC_KEYS = {"normal": "spec_n", "nb": "spec_nb",
             "perm": "spec_perm", "true": "spec_true"}
SPEC_KEYS.update({m: f"spec_{m}" for m in PROJ_METHODS})


##############################################################
# functions to create the pkl objects with the analytic PCA
# and the different empirical PCAs generated by different log-normalized count
# matrices: 
#  normal:  spike + gaussian noise
#  nb:  counts generated by a nb, then log-normalized + PCA
#  perm:  counts permuted within cell types, then log-normalized + PCA
#  true:  true counts, then log-normalized + PCA
#  analytic:  the model's own predicted PCA (the reference)

def permute_genes_within_celltype(X, cell_types):
    cell_types = np.asarray(cell_types)
    n_genes = X.shape[1]
    X = np.asarray(X)

    permuted = np.empty_like(X)
    for ct in np.unique(cell_types):
        idx = np.where(cell_types == ct)[0]
        n_ct = len(idx)

        block = X[idx, :]

        # independent random permutation of rows for each gene column
        perm_idx = np.argsort(np.random.rand(n_ct, n_genes), axis=0)
        permuted[idx, :] = np.take_along_axis(block, perm_idx, axis=0)

    return permuted


def simulate_projected_specs(pca_theory, spec_base, cell_labels, base_name):
    """The four spec_<base_name>_proj_i specs, one per rank in PROJ_RANKS.

    The analytic model's per-metacell moments are carried onto spec_base's
    basis (analysis_spike_util.compute_spike_projection), corrected toward
    spec_base's own empirical covariances by the best PSD rank-i term
    (rank_adjust_spike_projection), and sampled one cell per row of
    cell_labels (simulate_spike_projection). Rank 0 is the uncorrected
    projection, so the series shows what each extra correction rank buys.

    Each rank starts from a fresh copy of the unadjusted projection, so rank i
    is fitted from scratch rather than on top of rank i-1's correction
    (rank_adjust_spike_projection does not mutate its argument, but the copy
    makes that independence explicit).

    Every spec is {'sv': column norms of Y, 'U': Y with unit-norm columns,
    'V': None}, so U*sv == Y exactly and sv means what it does for the
    SVD-derived specs -- their U is orthonormal, so their sv_j is likewise
    ||Y[:, j]||. Unlike those, these columns are not orthogonal to one
    another, and there is no V because nothing was decomposed.
    """
    sp = asu.compute_spike_projection(pca_theory, spec_base, cell_labels)

    specs = {}
    for i in PROJ_RANKS:
        sp_i = {key: np.array(value, copy=True) for key, value in sp.items()}
        sp_i = asu.rank_adjust_spike_projection(sp_i, spec_base, cell_labels,
                                                rank_adjust=i)
        Y_i = asu.simulate_spike_projection(sp_i, cell_labels)
        sv_i = np.linalg.norm(Y_i, axis=0)
        U_i = np.divide(Y_i, sv_i, out=np.zeros_like(Y_i), where=sv_i > 0)
        specs[f"spec_{base_name}_proj_{i}"] = {'sv': sv_i, 'U': U_i, 'V': None}
    return specs


def reorder_rows_to_match_labels(U, source_labels, target_labels):
    """Permute the rows of `U` (each currently tagged by source_labels) so
    that row i instead corresponds to target_labels[i], one to one.

    `source_labels` and `target_labels` must contain the same labels with the
    same per-label counts (only the row order differs) -- rows sharing a
    label are exchangeable, so any 1-to-1 pairing between the two orderings
    is valid.
    """
    source_labels = np.asarray(source_labels)
    target_labels = np.asarray(target_labels)
    if len(source_labels) != len(target_labels):
        raise ValueError("source_labels and target_labels must have the same length")

    perm = np.empty(len(target_labels), dtype=int)
    for label in np.unique(target_labels):
        source_idx = np.where(source_labels == label)[0]
        target_idx = np.where(target_labels == label)[0]
        if len(source_idx) != len(target_idx):
            raise ValueError(f"label '{label}' has {len(source_idx)} rows in source_labels "
                             f"but {len(target_idx)} rows in target_labels")
        perm[target_idx] = source_idx

    return U[perm]


def get_spike_filename(dataset, n_genes, refined=False):
    """Path of the spec pkl, creating the folder if it does not exist.

    Holds the spec_* dicts only; the analytic PCA it was built from lives
    alongside it under get_pca_filename. Refined and unrefined pkls live in
    separate folders rather than being distinguished by a filename suffix,
    mirroring how the HVG h5ads they are built from are split across
    analysis_HVG and analysis_HVG_refined.
    """
    out_dir = SPIKE_REFINED_DIR if refined else SPIKE_DIR
    os.makedirs(out_dir, exist_ok=True)
    return os.path.join(out_dir, f"{dataset}_HVG_{n_genes}.pkl")


def get_pca_filename(dataset, n_genes, refined=False):
    """Path of the analytic-PCA pkl, creating the folder if it does not exist.

    Split out from the spec pkl because log_normalized_PCA dominates the cost
    of anndata2spike -- 69-80% of its runtime, growing with k^2 -- while the
    spec_* dicts around it take seconds. Keeping them apart means a new spec
    method can be added without paying for the analytic PCA again.
    """
    out_dir = SPIKE_REFINED_DIR if refined else SPIKE_DIR
    os.makedirs(out_dir, exist_ok=True)
    return os.path.join(out_dir, f"{dataset}_HVG_{n_genes}_pca.pkl")


def has_spike_result(dataset, n_genes, refined=False):
    """True when both halves of the split result are on disk. Consumers want
    the merged dict, so either half alone is not usable."""
    return (os.path.isfile(get_pca_filename(dataset, n_genes, refined=refined))
            and os.path.isfile(get_spike_filename(dataset, n_genes, refined=refined)))


def load_spike_result(dataset, n_genes, refined=False):
    """Both halves merged into one dict: the spec_* entries plus "pca_theory".

    Every consumer wants the two together, so the split is an on-disk detail
    that stops here rather than propagating outwards.
    """
    pca_f = get_pca_filename(dataset, n_genes, refined=refined)
    spec_f = get_spike_filename(dataset, n_genes, refined=refined)
    for f in (pca_f, spec_f):
        if not os.path.isfile(f):
            raise FileNotFoundError(
                f"{f} not found; build it with "
                f"anndata2spike('{dataset}', {n_genes}, refined={refined})")
    with open(spec_f, "rb") as f:
        result = pickle.load(f)
    with open(pca_f, "rb") as f:
        result["pca_theory"] = pickle.load(f)
    return result


def anndata2spike(dataset, n_genes, overwrite=False, refined=False):
    """Build (or load) the analytic PCA and the spec_* dicts, cached as two
    pkls under get_pca_filename and get_spike_filename.

    One `overwrite` flag covers both, but the halves are not independent:

        overwrite    pca pkl   spec pkl   action
        True         -         -          recompute both
        False        missing   either     recompute both
        False        exists    missing    load the pca, recompute the specs
        False        exists    exists     load both

    Row 3 is the point of the split -- log_normalized_PCA dominates the cost,
    so adding a spec method costs seconds rather than minutes. Row 2 rebuilds
    the specs even when they are present, because spec_analytic is derived from
    pca_theory: pairing an old spec pkl with a freshly computed PCA would
    silently mix two different k and two different eigenbases.

    nb["L"] is per metacell (each metacell's mean library size), and it is
    the library size behind everything here: spec_nb draws each metacell's
    cells at its own L, and pca_theory, spec_analytic, spec_n and the
    <base>_proj_i specs evaluate the analytic model at the same per-metacell
    L.

    Every spec carries "U", "sv" and "V". U's rows follow the h5ad's cell order
    for ALL specs including spec_analytic, which is realigned here out of
    pca_theory's own sample_labels order -- so the specs are row-comparable to
    one another, while pca_theory itself keeps its original ordering.

    "cell_labels" is stored alongside the specs: the h5ad's metacell column, one
    entry per row, in the specs' own row order.

    V holds the right singular vectors (gene loadings), p x k. For nb/perm/true
    /normal it is the SVD's own V; spec_analytic has no SVD behind it, so it
    carries pca_theory's mean_gene_matrix, the model's predicted gene loading
    per PC. Note that one is NOT orthonormal (column norms ~0.97-1.00, Gram
    off-diagonals up to 0.008), unlike the four empirical V's.
    """
    pca_f = get_pca_filename(dataset, n_genes, refined=refined)
    spec_f = get_spike_filename(dataset, n_genes, refined=refined)
    have_pca = os.path.isfile(pca_f) and not overwrite

    if have_pca and os.path.isfile(spec_f):
        result = load_spike_result(dataset, n_genes, refined=refined)
        # a pkl written before perm_proj existed simply lacks those keys; they
        # come back as None rather than raising, so old caches stay readable
        # until they are rebuilt with overwrite=True
        return (result["pca_theory"], result["spec_analytic"], result["spec_nb"],
                result["spec_perm"], result["spec_true"], result["spec_n"],
                *(result.get(SPEC_KEYS[m]) for m in PROJ_METHODS))

    s = (dr.load_HVG_refined_dataset(dataset, n_genes) if refined
         else datasets.load_HVG_dataset(dataset, n_genes))
    n = s.n_obs
    nb = s.uns["nb_model"]

    if have_pca:
        print(f"Loading the cached analytic PCA from {os.path.basename(pca_f)}")
        with open(pca_f, "rb") as f:
            pca_theory = pickle.load(f)
    else:
        pca_theory = lwa.log_normalized_PCA(nb, s.n_obs)
        with open(pca_f, "wb") as f:
            pickle.dump(pca_theory, f)

    cell_labels = s.obs["metacell"].to_numpy()

    # every cell of a metacell is drawn at that metacell's own library size
    # nb["L"][i], the same per-metacell L the analytic PCA and the normal
    # model below are built at
    print("Simulating the NB data")
    X = nb_model.simulate_X(nb, cell_labels)
    s_nb = sc.AnnData(X)
    sc.pp.normalize_total(s_nb, target_sum=1e4)
    sc.pp.log1p(s_nb)
    sc.pp.scale(s_nb)
    U_nb, sv_nb, Vt_nb = np.linalg.svd(s_nb.X, full_matrices=False)

    print("Permuting the genes within cell types")
    X_true = s.X.toarray()
    X_true_permuted = permute_genes_within_celltype(X_true, cell_labels)
    s_perm = sc.AnnData(X_true_permuted)
    sc.pp.normalize_total(s_perm, target_sum=1e4)
    sc.pp.log1p(s_perm)
    sc.pp.scale(s_perm)
    U_perm, sv_perm, Vt_perm = np.linalg.svd(s_perm.X, full_matrices=False)

    print("Computing the PCA eigenvalues")
    s_new = s.copy()
    sc.pp.normalize_total(s_new, target_sum=1e4)
    sc.pp.log1p(s_new)
    sc.pp.scale(s_new)
    U_true, sv_true, Vt_true = np.linalg.svd(s_new.X, full_matrices=False)

    print("Compute Normal Noise Model")
    m_model, spike = lwa.log_normalized_spiked_mixture_model(nb, s.shape[0], include_spike=True)
    Z = lwa.simulate_Z_guassian(m_model, spike)
    U_n, sv_n, Vt_n = np.linalg.svd(Z, full_matrices=False)
    U_n = reorder_rows_to_match_labels(U_n, spike["sample_labels"], cell_labels)

    k = len(pca_theory["values"])
    # spec_analytic is realigned into the h5ad's cell order so every spec
    # shares one row order; pca_theory keeps its own sample_labels ordering.
    # Its V is the model's predicted gene loading rather than an SVD factor.
    U_analytic = reorder_rows_to_match_labels(
        pca_theory["vectors"][:, :k], pca_theory["sample_labels"], cell_labels)
    spec_analytic = {'sv': pca_theory["values"][:k], 'U': U_analytic,
                     'V': np.asarray(pca_theory["mean_gene_matrix"])[:, :k]}
    spec_nb = {'sv': sv_nb[:k]/np.sqrt(n), 'U': U_nb[:, :k], 'V': Vt_nb[:k, :].T}
    spec_perm = {'sv': sv_perm[:k]/np.sqrt(n), 'U': U_perm[:, :k], 'V': Vt_perm[:k, :].T}
    spec_true = {'sv': sv_true[:k]/np.sqrt(n), 'U': U_true[:, :k], 'V': Vt_true[:k, :].T}
    spec_n = {'sv': sv_n[:k], 'U': U_n[:, :k], 'V': Vt_n[:k, :].T}

    # one <base>_proj_i family per PROJ_BASES entry -- see
    # simulate_projected_specs for what they are
    spec_proj = {}
    base_specs = {"perm": spec_perm, "true": spec_true}
    for base_name in PROJ_BASES:
        print(f"Simulating the projected analytic specs against {base_name}")
        spec_proj.update(simulate_projected_specs(
            pca_theory, base_specs[base_name], cell_labels, base_name))

    # pca_theory is deliberately absent here -- it is the other pkl, and
    # load_spike_result puts the two back together
    # cell_labels rides along so consumers can group the spec rows by metacell
    # without reopening the h5ad. It CANNOT be recovered from pca_theory:
    # pca_theory["sample_labels"] describes that object's own row order, which
    # is contiguous metacell blocks, whereas the specs follow the h5ad's
    # shuffled cell order (apply_metacell_decomposition sorts then shuffles).
    # The two are the same multiset but agree in only ~2-5% of positions.
    result = {"spec_analytic": spec_analytic, "spec_nb": spec_nb,
              "spec_perm": spec_perm, "spec_true": spec_true, "spec_n": spec_n,
              "cell_labels": cell_labels}
    result.update(spec_proj)
    with open(spec_f, "wb") as f:
        pickle.dump(result, f)

    return (pca_theory, spec_analytic, spec_nb, spec_perm, spec_true, spec_n,
            *(spec_proj[SPEC_KEYS[m]] for m in PROJ_METHODS))


def make_all_spike_pkl(datasets_list=datasets.DEFAULT_DATASETS,
                       n_genes_list=datasets.DEFAULT_N_GENES,
                       overwrite=False, refined=False):
    for dataset in datasets_list:
        for n_genes in n_genes_list:
            print(f"Processing {dataset} HVG {n_genes}")
            try:
                anndata2spike(dataset, n_genes, overwrite=overwrite, refined=refined)
            except ValueError as e:
                # the HVG h5ad for this combination has not been built yet;
                # skip it rather than abandoning the rest of the sweep
                print(f"  SKIPPING {dataset}/{n_genes}: {e}")
    return None




def _load_spike_entries(refined=False, dataset_list=None, n_genes_list=None):
    """(dataset, n_genes, result) for every cached spike pkl.

    Purely a reader -- a combination whose pkl has not been built is skipped
    rather than triggering anndata2spike, which takes minutes.
    """
    dataset_list = datasets.DEFAULT_DATASETS if dataset_list is None else dataset_list
    n_genes_list = datasets.DEFAULT_N_GENES if n_genes_list is None else n_genes_list

    entries = []
    for dataset in dataset_list:
        for n_genes in n_genes_list:
            if not has_spike_result(dataset, n_genes, refined=refined):
                continue
            entries.append((dataset, n_genes,
                            load_spike_result(dataset, n_genes, refined=refined)))
    return entries

##############################################################################
# LEGACY CODE
def compute_analytic_mixture_axes(pca_theory, mixture_labels, k, random_basis=False):
    """Per-mixture analytic mean, PC-score covariance eigenbasis, and the
    mean/sd expressed along that eigenbasis.

    For each mixture label, M_sv (the k x k analytic covariance of the PC
    scores U*sv, from get_GMM) is diagonalized M_sv = Q @ diag(eigvals) @ Q.T
    with Q orthogonal and eigvals sorted descending (so axis 0 is still the
    highest-variance direction, matching the old raw-PC-axis convention).

    If random_basis is True, Q is instead a freshly drawn random orthogonal
    k x k matrix (via QR decomposition of a random Gaussian matrix) rather
    than M_sv's eigenvectors -- there is no eigenvalue to sort by in that
    case, so the sd along each of its columns is computed with the general
    quadratic form diag(Q.T @ M_sv @ Q), which is equivalent to sqrt(eigvals)
    when Q is the eigenvector basis but also valid for an arbitrary
    orthogonal Q.

    Returns five lists aligned with mixture_labels:
    - means: raw (unrotated) first-k GMM mean vectors -- kept around because
      determine_axis_signs needs to compare against other methods' raw means
      before anyone is rotated (see determine_axis_signs).
    - Qs: the k x k orthogonal basis matrices.
    - rotated_means: means projected onto Q's columns (Q.T @ mean).
    - rotated_sds: the analytic sd along Q's columns.
    - covariances: M_sv itself (raw, unrotated k x k analytic covariance) --
      kept around as the W_a reference for compute_rotated_empirical_moments's
      independence metric.
    """
    means = []
    Qs = []
    rotated_means = []
    rotated_sds = []
    covariances = []
    for label in mixture_labels:
        gmm = lwa.get_GMM(pca_theory, label)
        mean = np.asarray(gmm["mean"])[:k]
        M_sv = np.asarray(gmm["covariance"])[:k, :k]

        if random_basis:
            Q, _ = np.linalg.qr(np.random.randn(k, k))
            rotated_sd = np.sqrt(np.clip(np.diag(Q.T @ M_sv @ Q), 0, None))
        else:
            eigvals, Q = np.linalg.eigh(M_sv)
            order = np.argsort(eigvals)[::-1]
            eigvals, Q = eigvals[order], Q[:, order]
            rotated_sd = np.sqrt(np.clip(eigvals, 0, None))

        means.append(mean)
        Qs.append(Q)
        rotated_means.append(Q.T @ mean)
        rotated_sds.append(rotated_sd)
        covariances.append(M_sv)
    return means, Qs, rotated_means, rotated_sds, covariances


def determine_axis_signs(spec, cell_labels, mixture_labels, k, analytic_means):
    """Length-k array of +-1, one per raw (unrotated) PC axis, chosen so that
    this method's raw per-mixture mean best matches the analytic raw
    per-mixture mean (`analytic_means`, aligned with mixture_labels -- see
    compute_analytic_mixture_axes), pooling the sign choice across all
    mixture labels since a PC's eigenvector has a single sign for the whole
    dataset, not one free per mixture.

    This must run, and be applied, before projecting through a mixture's Q
    (see compute_rotated_empirical_moments): once axes are mixed by a
    rotation, a wrong sign on one input axis corrupts every rotated
    coordinate, not just the one it started on, so a post-hoc scalar sign
    flip on the rotated output can no longer undo it.
    """
    pc_scores = spec["U"][:, :k] * spec["sv"][:k]
    raw_means = np.zeros((len(mixture_labels), k))
    for m, label in enumerate(mixture_labels):
        mask = cell_labels == label
        raw_means[m, :] = pc_scores[mask, :].mean(axis=0)

    analytic = np.asarray(analytic_means)
    # sign that maximizes sum(sign * mean * analytic_mean), i.e. minimizes
    # sum((sign * mean - analytic_mean)**2) over sign in {+1, -1}, pooled
    # across mixture labels (axis 0)
    dot = (raw_means * analytic).sum(axis=0)
    return np.where(dot >= 0, 1.0, -1.0)


def compute_rotated_empirical_moments(spec, cell_labels, mixture_labels, k, sign, Qs,
                                       analytic_covariances):
    """Empirical mean, std, normality, and independence for this method,
    each mixture's PC scores projected into that mixture's own analytic
    covariance eigenbasis (Qs, aligned with mixture_labels -- see
    compute_analytic_mixture_axes).

    `sign` (from determine_axis_signs) is applied to the raw PC axes before
    rotating through Q, resolving this method's SVD sign ambiguity against
    the analytic axes.

    `normality` is the max absolute difference between the empirical CDF and
    the CDF of a normal distribution fit to that same rotated sample's
    mean/std -- see normality.max_ecdf_normal_diff.

    `independence` is ||W - W_a|| / ||W_a|| (Frobenius norm), where W is this
    method's empirical k x k covariance matrix of (sign-corrected) U*sv for
    that mixture's cells, and W_a is analytic_covariances[mixture_idx] (M_sv,
    from compute_analytic_mixture_axes) -- how far this method's whole
    covariance structure is from the analytic model's prediction for that
    mixture, as a fraction of the analytic covariance's own size. This is
    computed on the raw (unrotated) sign-corrected scores rather than the
    Q-rotated ones -- a Frobenius norm is invariant to rotating both W and
    W_a by the same orthogonal Q, so the value is identical either way, but
    sign correction still matters here (unlike the rotation): W_a sits in
    analytic's own fixed sign convention, while a method's raw axes have an
    arbitrary SVD sign with no reason to match it, and (unlike variances) the
    off-diagonal covariance entries flip sign with a mismatched axis sign. It
    is a joint property of the whole covariance matrix, so it is the same
    value for all k rows of a given mixture.

    Returns four flat arrays aligned with itertools.product(mixture_labels, range(k)).
    """
    # local import: normality imports this module at top level, so a
    # top-level import here would be circular
    import normality as nrm

    pc_scores = spec["U"][:, :k] * spec["sv"][:k] * sign[np.newaxis, :]

    means, stds, normality, independence = [], [], [], []
    for label, Q, W_a in zip(mixture_labels, Qs, analytic_covariances):
        mask = cell_labels == label
        rotated = pc_scores[mask, :] @ Q

        W = np.cov(pc_scores[mask, :], rowvar=False)
        indep = np.linalg.norm(W - W_a, ord="fro") / np.linalg.norm(W_a, ord="fro")

        for j in range(k):
            group = rotated[:, j]
            mean_j, std_j = group.mean(), group.std()
            means.append(mean_j)
            stds.append(std_j)
            normality.append(nrm.max_ecdf_normal_diff(group, mean_j, std_j))
            independence.append(indep)
    return np.array(means), np.array(stds), np.array(normality), np.array(independence)


def build_spike_moments_df(dataset_names=datasets.DEFAULT_DATASETS, n_genes_list=datasets.DEFAULT_N_GENES,
                            random_basis=False, refined=False):
    """Long-format table of GMM/empirical mean, standard deviation, and
    normality, each measured along the analytic covariance's own principal
    axes rather than the raw PCA axes.

    For each (dataset, n_genes, mixture_label), the analytic PC-score
    covariance M_sv is diagonalized as Q @ diag(eigvals) @ Q.T (see
    compute_analytic_mixture_axes); every method's per-cell PC scores
    (sign-corrected against the analytic raw axes first -- see
    determine_axis_signs) are projected onto Q's columns before mean/sd/
    normality/independence are computed (see compute_rotated_empirical_moments).
    So "pca_idx" here indexes a mixture-specific rotated axis (0 = highest
    analytic variance for that mixture), not a direction shared across
    mixture labels the way the raw PCA axes were.

    If random_basis is True, Q is a random orthogonal matrix instead of
    M_sv's eigenvectors (see compute_analytic_mixture_axes) -- "pca_idx"
    then just indexes one of k random orthogonal directions per mixture,
    with no eigenvalue ordering behind it.

    One row per (dataset, n_genes, mixture_label, pca_idx, method), with
    method in {"analytic", "normal", "nb", "perm", "true"}. mixture_label/pca_idx are
    kept (beyond dataset/n_genes/method/mean/sd/normality/independence) so that
    rows can be re-aligned across methods later (e.g. pivoted to plot
    nb/perm/true vs analytic).

    `normality` is the max absolute difference between the empirical CDF and
    a fitted normal CDF (see normality.max_ecdf_normal_diff); it is trivially 0 for
    "analytic" rows since the analytic theory is assumed exactly Gaussian.

    `independence` is ||W - W_a|| / ||W_a|| (Frobenius norm), the relative
    distance between this method's empirical k x k covariance matrix of
    (sign-corrected) U*sv for that mixture and the analytic covariance M_sv
    predicts for it (see compute_rotated_empirical_moments). It is a joint
    property of the whole covariance matrix for a given mixture, so it is
    constant across pca_idx within a (dataset, n_genes, mixture_label,
    method) group; it is trivially 0 for "analytic" rows since W = W_a there
    by construction.
    """
    rows = []
    for dataset in dataset_names:
        for n_genes in n_genes_list:
            if not has_spike_result(dataset, n_genes, refined=refined):
                continue

            result = load_spike_result(dataset, n_genes, refined=refined)

            # the h5ad must come from the same partition as the pkl -- the
            # cell labels below are matched against it row for row
            s = (dr.load_HVG_refined_dataset(dataset, n_genes) if refined
                 else datasets.load_HVG_dataset(dataset, n_genes))
            cell_labels = s.obs["metacell"].to_numpy()
            mixture_labels = np.unique(cell_labels)
            k = result["spec_nb"]["U"].shape[1]

            analytic_means, Qs, analytic_rotated_means, analytic_rotated_sds, analytic_covariances = (
                compute_analytic_mixture_axes(result["pca_theory"], mixture_labels, k, random_basis))

            # a second, independent draw from the same analytic GMM (same
            # mean/covariance as the analytic model, fresh randomness), to see
            # how much of the reference normality/independence is sampling noise.
            # Rows already come out in cell_labels order (see
            # simulate_PCA_embedding), so no realignment is needed here.
            pca_theory = result["pca_theory"]
            spec_gmm_resampled = lwa.simulate_PCA_embedding(pca_theory, cell_labels)

            # driven by SPIKE_METHODS rather than a local list, so a method
            # added there (e.g. the pert_* perturbed-covariance draws) flows
            # into the moments df and its plots. A pkl written before a method
            # existed simply lacks the key and is skipped, so stale pkls still
            # work -- they just contribute no rows for that method.
            specs = {m: result[SPEC_KEYS[m]] for m in SPIKE_METHODS
                     if SPEC_KEYS[m] in result}
            missing = [m for m in SPIKE_METHODS if SPEC_KEYS[m] not in result]
            if missing:
                print(f"  {dataset}/{n_genes}: no {', '.join(missing)} in this pkl "
                      f"(rebuild with overwrite=True to add)")
            specs["gmm_resampled"] = spec_gmm_resampled
            empirical_moments = {}
            for method, spec in specs.items():
                sign = determine_axis_signs(spec, cell_labels, mixture_labels, k, analytic_means)
                empirical_moments[method] = compute_rotated_empirical_moments(
                    spec, cell_labels, mixture_labels, k, sign, Qs, analytic_covariances)

            idx = 0
            for mixture_idx, mixture_label in enumerate(mixture_labels):
                for pca_idx in range(k):
                    moments_by_method = {"analytic": (analytic_rotated_means[mixture_idx][pca_idx],
                                                        analytic_rotated_sds[mixture_idx][pca_idx], 0.0, 0.0),
                                        **{method: (means[idx], stds[idx], normality[idx], independence[idx])
                                           for method, (means, stds, normality, independence)
                                           in empirical_moments.items()}}
                    for method, (mean, sd, normality_val, independence_val) in moments_by_method.items():
                        rows.append({"dataset": dataset, "n_genes": n_genes,
                                    "mixture_label": mixture_label, "pca_idx": pca_idx,
                                    "method": method, "mean": mean, "sd": sd,
                                    "normality": normality_val, "independence": independence_val})
                    idx += 1

    return pd.DataFrame(rows)


def _plot_spike_moments_from_df(df):
    df = df[df["pca_idx"] < 5]

    id_cols = ["dataset", "n_genes", "mixture_label", "pca_idx"]
    wide_mean = df.pivot(index=id_cols, columns="method", values="mean").reset_index()
    wide_sd = df.pivot(index=id_cols, columns="method", values="sd").reset_index()

    plotted_datasets = sorted(wide_mean["dataset"].unique())
    cmap = plt.get_cmap("tab10")
    colors = {dataset: cmap(i % 10) for i, dataset in enumerate(plotted_datasets)}

    # panels follow SPIKE_METHODS, minus any method the df has no rows for
    # (an older pkl that predates it) -- dropped rather than drawn empty
    panels = [m for m in SPIKE_METHODS if m in wide_mean.columns]
    fig, axes = plt.subplots(2, len(panels), figsize=(5 * len(panels), 10),
                             squeeze=False)

    row_specs = [(wide_mean, "mean", True), (wide_sd, "sd", False)]
    for row, (wide, value_label, signed) in enumerate(row_specs):
        for col, method in enumerate(panels):
            ax = axes[row, col]

            # drop points whose x (analytic) or y (method) value falls in
            # the upper/lower 2% quantile of that panel's own x or y column,
            # before plotting or fitting anything in this panel
            x_lo, x_hi = wide["analytic"].quantile([0.02, 0.98])
            y_lo, y_hi = wide[method].quantile([0.02, 0.98])
            panel = wide[wide["analytic"].between(x_lo, x_hi) & wide[method].between(y_lo, y_hi)]

            for dataset in plotted_datasets:
                sub = panel[panel["dataset"] == dataset]
                ax.scatter(sub["analytic"], sub[method], color=colors[dataset],
                          label=dataset, alpha=0.5, s=10)

            if value_label == "sd" and method == "true":
                lim = [0, 0.04]
            else:
                max_val = max(panel["analytic"].abs().max(), panel[method].abs().max())
                lim = [-max_val * 1.1, max_val * 1.1] if signed else [0, max_val * 1.1]
            ax.plot(lim, lim, color="black", ls="--", lw=1, label="x = y")

            x = panel["analytic"].to_numpy()
            y = panel[method].to_numpy()
            valid = np.isfinite(x) & np.isfinite(y)
            x_valid, y_valid = x[valid], y[valid]
            slope, intercept = np.polyfit(x_valid, y_valid, 1)

            if value_label == "sd":
                x_line = np.array(lim)
                ax.plot(x_line, slope * x_line + intercept, color="red", ls="--",
                        lw=1.5, label="regression")

            y_pred = slope * x_valid + intercept
            ss_res = np.sum((y_valid - y_pred) ** 2)
            ss_tot = np.sum((y_valid - y_valid.mean()) ** 2)
            r2 = 1 - ss_res / ss_tot
            ax.text(0.95, 0.95, f"$R^2$ = {r2:.2g}", transform=ax.transAxes,
                   ha="right", va="top")

            ax.set_xlim(lim)
            ax.set_ylim(lim)
            ax.set_xlabel(f"analytic {value_label}")
            ax.set_ylabel(f"{method} {value_label}")
            ax.set_title(f"{method} vs analytic {value_label}")
            ax.legend(fontsize=7)

    fig.tight_layout()
    plt.show()
    return fig


def plot_spike_moments(dataset_names=datasets.DEFAULT_DATASETS, n_genes_list=datasets.DEFAULT_N_GENES,
                       refined=False):
    # pca_idx indexes each mixture's own Q columns, sorted by descending
    # analytic eigenvalue (see compute_analytic_mixture_axes), so
    # _plot_spike_moments_from_df's pca_idx < 5 filter keeps only the 5
    # highest-eigenvalue rotated axes per mixture
    df = build_spike_moments_df(dataset_names, n_genes_list, refined=refined)
    return _plot_spike_moments_from_df(df)


def plot_spike_moments_random(dataset_names=datasets.DEFAULT_DATASETS, n_genes_list=datasets.DEFAULT_N_GENES,
                              refined=False):
    # same as plot_spike_moments, except means/sds are measured along a
    # freshly drawn random orthogonal basis per mixture instead of the
    # eigenvectors of that mixture's analytic covariance (see
    # compute_analytic_mixture_axes's random_basis option) -- pca_idx < 5
    # here just keeps 5 of the k random directions, with no eigenvalue
    # ordering behind that choice
    df = build_spike_moments_df(dataset_names, n_genes_list, random_basis=True, refined=refined)
    return _plot_spike_moments_from_df(df)


def compute_mixture_means(spec, cell_labels, mixture_labels, k):
    """dict label -> raw (unrotated) k-dim mean PC-score vector (mean of
    spec["U"][:,:k]*spec["sv"][:k]) for that mixture's cells.
    """
    pc_scores = spec["U"][:, :k] * spec["sv"][:k]
    means = {}
    for label in mixture_labels:
        mask = cell_labels == label
        means[label] = pc_scores[mask, :].mean(axis=0)
    return means


DEFAULT_NEIGHBOR_RANKS = [1, 20, 40]


def find_nearest_neighbors(means_by_label, neighbor_ranks=DEFAULT_NEIGHBOR_RANKS):
    """dict label -> list of (rank, neighbor_label) for each rank in
    neighbor_ranks (1 = closest other label by Euclidean distance between
    means, 2 = second closest, etc.). If a label doesn't have that many other
    labels available, that rank falls back to the farthest available one
    instead of being omitted. A label with no other labels at all yields no
    entries.
    """
    labels = list(means_by_label.keys())
    neighbors = {}
    for label in labels:
        mean = means_by_label[label]
        others = [other for other in labels if other != label]
        others.sort(key=lambda other: np.linalg.norm(means_by_label[other] - mean))
        n_others = len(others)
        neighbors[label] = [(rank, others[rank - 1] if rank <= n_others else others[-1])
                            for rank in neighbor_ranks if n_others > 0]
    return neighbors


def compute_projected_moments_empirical(spec, cell_labels, mixture_labels, k,
                                         neighbor_ranks=DEFAULT_NEIGHBOR_RANKS):
    """For each mixture, find its neighbors at each rank in neighbor_ranks
    (see find_nearest_neighbors, using this method's own raw per-mixture
    means); for each one, project both mixtures' raw PC scores onto the line
    through their two means, and return the projected mean/sd of each.

    Returns a dict label -> list of (neighbor_rank, neighbor_label,
    projected_mean, projected_sd, neighbor_mean, neighbor_sd), one entry per
    requested rank. The projection is
    an unshifted dot product with the unit direction from this mixture's
    mean to its neighbor's, so neighbor_mean - projected_mean recovers
    (approximately) the distance between the two means. Because the
    direction is derived purely from this method's own mean vectors, both it
    and the projected values are invariant to the arbitrary per-axis sign of
    spec["U"] (a sign flip rotates the direction and the scores together,
    leaving their dot product unchanged) -- no sign correction against the
    analytic axes is needed here.
    """
    pc_scores = spec["U"][:, :k] * spec["sv"][:k]
    means_by_label = compute_mixture_means(spec, cell_labels, mixture_labels, k)
    neighbors = find_nearest_neighbors(means_by_label, neighbor_ranks)

    results = {}
    for label in mixture_labels:
        mask = cell_labels == label
        entries = []
        for neighbor_rank, neighbor_label in neighbors[label]:
            direction = means_by_label[neighbor_label] - means_by_label[label]
            d_hat = direction / np.linalg.norm(direction)

            proj = pc_scores[mask, :] @ d_hat
            projected_mean, projected_sd = proj.mean(), proj.std()

            neighbor_mask = cell_labels == neighbor_label
            neighbor_proj = pc_scores[neighbor_mask, :] @ d_hat
            neighbor_mean, neighbor_sd = neighbor_proj.mean(), neighbor_proj.std()

            entries.append((neighbor_rank, neighbor_label, projected_mean, projected_sd,
                            neighbor_mean, neighbor_sd))
        results[label] = entries
    return results


def compute_projected_moments_analytic(pca_theory, mixture_labels, k,
                                        neighbor_ranks=DEFAULT_NEIGHBOR_RANKS):
    """Analytic counterpart of compute_projected_moments_empirical: the same
    neighbor-rank lines (using analytic GMM means -- see get_GMM), but
    projected/neighbor mean and sd come from the analytic GMM mean/covariance
    directly rather than an empirical sample -- the mean of a linear
    projection is direction . mean, and its variance is
    direction @ covariance @ direction.
    """
    means_by_label = {}
    covariances_by_label = {}
    for label in mixture_labels:
        gmm = lwa.get_GMM(pca_theory, label)
        means_by_label[label] = np.asarray(gmm["mean"])[:k]
        covariances_by_label[label] = np.asarray(gmm["covariance"])[:k, :k].real

    neighbors = find_nearest_neighbors(means_by_label, neighbor_ranks)

    results = {}
    for label in mixture_labels:
        entries = []
        for neighbor_rank, neighbor_label in neighbors[label]:
            direction = means_by_label[neighbor_label] - means_by_label[label]
            d_hat = direction / np.linalg.norm(direction)

            projected_mean = means_by_label[label] @ d_hat
            projected_sd = np.sqrt(d_hat @ covariances_by_label[label] @ d_hat)
            neighbor_mean = means_by_label[neighbor_label] @ d_hat
            neighbor_sd = np.sqrt(d_hat @ covariances_by_label[neighbor_label] @ d_hat)

            entries.append((neighbor_rank, neighbor_label, projected_mean, projected_sd,
                            neighbor_mean, neighbor_sd))
        results[label] = entries
    return results


def build_neighbor_moments_df(dataset_names=datasets.DEFAULT_DATASETS, n_genes_list=datasets.DEFAULT_N_GENES,
                               neighbor_ranks=DEFAULT_NEIGHBOR_RANKS):
    """Long-format table of nearest-neighbor-line projected mean/sd.

    For each (dataset, n_genes, method, mixture_label): find its neighbor at
    each rank in neighbor_ranks within that method (see
    find_nearest_neighbors), and for each one, project both mixtures' PC
    scores onto the line between their means and report the projected
    mean/sd of this mixture and of that neighbor (see
    compute_projected_moments_empirical and compute_projected_moments_analytic).

    Up to len(neighbor_ranks) rows per (dataset, n_genes, mixture_label,
    method), method in {"analytic", "normal", "nb", "perm", "true"},
    distinguished by neighbor_rank (1 = closest neighbor, 5 = 5th closest, ...).
    """
    rows = []
    for dataset in dataset_names:
        for n_genes in n_genes_list:
            out_f = get_spike_filename(dataset, n_genes)
            if not os.path.isfile(out_f):
                continue

            with open(out_f, "rb") as f:
                result = pickle.load(f)

            s = datasets.load_HVG_dataset(dataset, n_genes)
            cell_labels = s.obs["metacell"].to_numpy()
            mixture_labels = np.unique(cell_labels)
            k = result["spec_nb"]["U"].shape[1]

            specs = {"nb": result["spec_nb"], "perm": result["spec_perm"], "true": result["spec_true"],
                    "analytic": result["spec_analytic"], "normal": result["spec_n"]}

            moments_by_method = {"analytic": compute_projected_moments_analytic(
                result["pca_theory"], mixture_labels, k, neighbor_ranks)}
            for method, spec in specs.items():
                moments_by_method[method] = compute_projected_moments_empirical(
                    spec, cell_labels, mixture_labels, k, neighbor_ranks)

            for method, moments in moments_by_method.items():
                for label, entries in moments.items():
                    for (neighbor_rank, neighbor_label, projected_mean, projected_sd,
                         neighbor_mean, neighbor_sd) in entries:
                        rows.append({"dataset": dataset, "n_genes": n_genes,
                                    "mixture_label": label, "method": method,
                                    "neighbor_rank": neighbor_rank, "neighbor_label": neighbor_label,
                                    "projected_mean": projected_mean, "projected_sd": projected_sd,
                                    "neighbor_mean": neighbor_mean, "neighbor_sd": neighbor_sd})

    return pd.DataFrame(rows)


def plot_neighbor_moments(dataset_names=datasets.DEFAULT_DATASETS, n_genes_list=datasets.DEFAULT_N_GENES,
                           neighbor_ranks=DEFAULT_NEIGHBOR_RANKS):
    df = build_neighbor_moments_df(dataset_names, n_genes_list, neighbor_ranks)
    df["ratio"] = ((df["projected_mean"] - df["neighbor_mean"]).abs()
                   / (df["projected_sd"] + df["neighbor_sd"]))

    id_cols = ["dataset", "n_genes", "mixture_label", "neighbor_rank"]
    wide_mean = df.pivot(index=id_cols, columns="method", values="projected_mean").reset_index()
    wide_sd = df.pivot(index=id_cols, columns="method", values="projected_sd").reset_index()
    wide_ratio = df.pivot(index=id_cols, columns="method", values="ratio").reset_index()
    for wide in (wide_mean, wide_sd, wide_ratio):
        wide["_key"] = list(zip(wide["dataset"], wide["n_genes"], wide["mixture_label"],
                                wide["neighbor_rank"]))

    # color points by neighbor_rank (1 = closest neighbor, ... furthest of the
    # requested ranks), not by dataset -- colored by position among the
    # requested ranks, not the rank value itself, since ranks needn't be
    # consecutive (e.g. 1, 5, 10, 15, 20)
    plotted_ranks = sorted(df["neighbor_rank"].unique())
    cmap = plt.get_cmap("viridis")
    colors = {rank: cmap(i / max(len(plotted_ranks) - 1, 1)) for i, rank in enumerate(plotted_ranks)}

    panels = ["normal", "nb", "perm", "true"]
    fig, axes = plt.subplots(3, 5, figsize=(25, 15))

    row_specs = [(wide_mean, "projected_mean", True), (wide_sd, "projected_sd", False),
                 (wide_ratio, "ratio", False)]
    # for each method, the set of (dataset, n_genes, mixture_label) keys that
    # survived the row-0 (mean) and row-1 (sd) outlier filters, so row 2
    # (ratio) can restrict itself to points kept in both -- see below
    kept_keys_by_method = {method: [] for method in panels}

    for row, (wide, value_label, signed) in enumerate(row_specs):
        for col, method in enumerate(panels):
            ax = axes[row, col]

            if row < 2:
                # drop points whose x (analytic) or y (method) value falls in
                # the upper/lower 2.5% quantile of that panel's own x or y
                # column, before plotting or fitting anything in this panel
                x_lo, x_hi = wide["analytic"].quantile([0.025, 0.975])
                y_lo, y_hi = wide[method].quantile([0.025, 0.975])
                panel = wide[wide["analytic"].between(x_lo, x_hi) & wide[method].between(y_lo, y_hi)]
                kept_keys_by_method[method].append(set(panel["_key"]))
            else:
                # ratio row: no new quantile trim of its own -- only keep
                # points that were not outliers in either of the mean/sd rows
                combined_keys = kept_keys_by_method[method][0] & kept_keys_by_method[method][1]
                panel = wide[wide["_key"].isin(combined_keys)]

            for rank in plotted_ranks:
                sub = panel[panel["neighbor_rank"] == rank]
                ax.scatter(sub["analytic"], sub[method], color=colors[rank],
                          label=f"neighbor {rank}", alpha=0.5, s=10)

            max_val = max(panel["analytic"].abs().max(), panel[method].abs().max())
            lim = [-max_val * 1.1, max_val * 1.1] if signed else [0, max_val * 1.1]
            ax.plot(lim, lim, color="black", ls="--", lw=1, label="x = y")

            x = panel["analytic"].to_numpy()
            y = panel[method].to_numpy()
            valid = np.isfinite(x) & np.isfinite(y)
            x_valid, y_valid = x[valid], y[valid]
            slope, intercept = np.polyfit(x_valid, y_valid, 1)

            y_pred = slope * x_valid + intercept
            ss_res = np.sum((y_valid - y_pred) ** 2)
            ss_tot = np.sum((y_valid - y_valid.mean()) ** 2)
            r2 = 1 - ss_res / ss_tot
            ax.text(0.95, 0.95, f"$R^2$ = {r2:.2g}", transform=ax.transAxes,
                   ha="right", va="top")

            ax.set_xlim(lim)
            ax.set_ylim(lim)
            ax.set_xlabel(f"analytic {value_label}")
            ax.set_ylabel(f"{method} {value_label}")
            ax.set_title(f"{method} vs analytic {value_label}")
            ax.legend(fontsize=7)

    fig.tight_layout()
    plt.show()
    return fig


def plot_spike_normality(dataset_names=datasets.DEFAULT_DATASETS, n_genes_list=datasets.DEFAULT_N_GENES,
                         refined=False):
    df = build_spike_moments_df(dataset_names, n_genes_list, refined=refined)

    panels = ["normal", "nb", "perm", "true"]
    fig, axes = plt.subplots(4, 5, figsize=(25, 20))

    for ax, method in zip(axes[0], panels):
        values = df.loc[df["method"] == method, "normality"]
        ax.hist(values, bins=30, color="steelblue", alpha=0.8)
        ax.set_xlabel("max |ECDF - normal CDF|")
        ax.set_ylabel("count")
        ax.set_title(f"{method}: normality")

    id_cols = ["dataset", "n_genes", "mixture_label", "pca_idx"]
    wide_normality = df.pivot(index=id_cols, columns="method", values="normality").reset_index()

    for col, method in enumerate(panels):
        ax = axes[1, col]
        # the gmm-vs-gmm panel is trivially y = x, so use gmm_resampled (an
        # independent draw from the same analytic mean/covariance) instead,
        # to see how much of the reference normality is just sampling noise
        y_method = "gmm_resampled" if method == "gmm" else method
        ax.scatter(wide_normality["analytic"], wide_normality[y_method], color="steelblue",
                  alpha=0.5, s=10)

        max_val = max(wide_normality["analytic"].max(), wide_normality[y_method].max())
        lim = [0, max_val * 1.1]
        ax.plot(lim, lim, color="black", ls="--", lw=1, label="x = y")
        ax.set_xlim(lim)
        ax.set_ylim(lim)
        ax.set_xlabel("analytic normality")
        ax.set_ylabel(f"{y_method} normality")
        ax.set_title(f"{y_method} vs analytic normality")
        ax.legend(fontsize=7)

    # independence is constant across pca_idx within a (dataset, n_genes,
    # mixture_label, method) group, so dedupe before histogramming/pivoting --
    # otherwise each mixture's value would be counted k times
    dedup = df.drop_duplicates(subset=["dataset", "n_genes", "mixture_label", "method"])
    for ax, method in zip(axes[2], panels):
        values = dedup.loc[dedup["method"] == method, "independence"]
        ax.hist(values, bins=30, color="darkorange", alpha=0.8)
        ax.set_xlabel(r"$\|corr - I\|_F$")
        ax.set_ylabel("count")
        ax.set_title(f"{method}: independence")

    indep_id_cols = ["dataset", "n_genes", "mixture_label"]
    wide_independence = dedup.pivot(index=indep_id_cols, columns="method", values="independence").reset_index()

    for col, method in enumerate(panels):
        ax = axes[3, col]
        # same gmm_resampled substitution as row 1, so the gmm panel isn't
        # trivially y = x here either
        y_method = "gmm_resampled" if method == "gmm" else method
        ax.scatter(wide_independence["analytic"], wide_independence[y_method], color="darkorange",
                  alpha=0.5, s=10)

        max_val = max(wide_independence["analytic"].max(), wide_independence[y_method].max())
        lim = [0, max_val * 1.1]
        ax.plot(lim, lim, color="black", ls="--", lw=1, label="x = y")
        ax.set_xlim(lim)
        ax.set_ylim(lim)
        ax.set_xlabel("analytic independence")
        ax.set_ylabel(f"{y_method} independence")
        ax.set_title(f"{y_method} vs analytic independence")
        ax.legend(fontsize=7)

    fig.tight_layout()
    plt.show()
    return fig


def plot_eigenvector_distribution(dataset, n_genes, mixture_label):
    pca_theory = anndata2spike(dataset, n_genes)[0]
    gmm = lwa.get_GMM(pca_theory, mixture_label)
    means, stds = gmm["mean"], gmm["std"]
    k = len(means)

    specs = {"nb": spec_nb, "perm": spec_perm, "true": spec_true}

    s = datasets.load_HVG_dataset(dataset, n_genes)
    mask = s.obs["metacell"].to_numpy() == mixture_label

    cmap = plt.get_cmap("viridis")
    color_norm = plt.Normalize(vmin=0, vmax=max(k - 1, 1))

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    for ax, label in zip(axes, ["nb", "perm", "true"]):
        for i in range(k):
            mean_i, std_i = means[i], stds[i]
            color = cmap(color_norm(i))

            # the eigenvector (and hence its PC score) is only defined up to
            # an overall sign; the analytic mean stays fixed, so flip this
            # eigenvector's sign if that fits the analytic GMM better
            pc_scores = specs[label]["U"][:, i] * specs[label]["sv"][i]
            group_scores = pc_scores[mask]
            emp_mean = group_scores.mean()
            if abs(emp_mean - mean_i) > abs(-emp_mean - mean_i):
                group_scores = -group_scores

            ax.hist(group_scores, bins=30, density=True, histtype="step",
                    color=color, linewidth=1)

            x_grid = np.linspace(mean_i - 4 * std_i, mean_i + 4 * std_i, 300)
            ax.plot(x_grid, norm.pdf(x_grid, mean_i, std_i),
                    color=color, linewidth=1.5, linestyle="--")

        ax.set_xlabel("PC score")
        ax.set_ylabel("density")
        ax.set_title(f"{dataset} HVG {n_genes}, mixture {mixture_label}: {label}")

    fig.tight_layout()

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=color_norm)
    sm.set_array([])
    fig.colorbar(sm, ax=axes, label="PC index", fraction=0.02, pad=0.02)

    # share x/y scale across panels; each panel's own autoscale already had
    # to fit every PC's +/-4*sd analytic window, so the union across panels
    # is guaranteed to include every PC's window in every panel
    x_lims = [ax.get_xlim() for ax in axes]
    y_lims = [ax.get_ylim() for ax in axes]
    shared_xlim = (min(lo for lo, _ in x_lims), max(hi for _, hi in x_lims))
    shared_ylim = (min(lo for lo, _ in y_lims), max(hi for _, hi in y_lims))
    for ax in axes:
        ax.set_xlim(shared_xlim)
        ax.set_ylim(shared_ylim)

    plt.show()
    return fig


#s = datasets.load_HVG_dataset("PBMC", 1000)
#_ = anndata2spike("PBMC", 2000)
#spec_analytic, spec_nb, spec_perm, spec_true = anndata2spike("Heart", 1000)
#_ = plot_spike_spectrum()
#_ = plot_spike_moments()
#_ = plot_spike_moments_random()
#_ = plot_spike_normality()
#_ = plot_neighbor_moments()