"""Build the manuscript's two tables under ../figures/:

  datasets.tex   Table \\ref{tab:datasets}, the dataset table, from the
                 refined 1000-gene HVG h5ads and refined spike pkls
                 (make_datasets_table)
  knn_table.tex  Table \\ref{tab:knn}, the per-dataset relative error of
                 the LML-RMT k-NN edge-fraction predictions, from the
                 refined knn pkls (make_knn_table)
  processing_table.tex
                 Table \\ref{tab:processing}, each dataset's source
                 identifier, QC cutoffs and pre-QC cell selection, from
                 the dataset_*.py modules' threshold constants and
                 PROCESSING_INFO (make_processing_table)

Run from python_CITEseq:

    python3 table.py

to build all three, or call any one function. The dataset table's rows are
datasets.DEFAULT_DATASETS in order; the knn table's rows are sorted by the
true count matrix's error. Everything is read from disk, so every dataset's
refined h5ad, spike pkl and knn pkl must exist (run make.make_all first).
The facts that are not on disk -- the citation key, the stage, the 10x
chemistry and, where the h5ad has no donor column, the donor count -- live
in DATASET_INFO below. Edit that dict, not the tex files: the tex files are
overwritten on every run.
"""
import os
import pickle

import anndata as ad
import numpy as np
import pandas as pd

import analysis_spike as asp
import datasets
import datasets_refined as dr
import figures_util as fu
import dataset_BMhemato
import dataset_BMMC
import dataset_Breast
import dataset_Breast_small
import dataset_Fat
import dataset_Ocular
import dataset_Skin
import dataset_thymus
import dataset_Zebrafish

TABLE_FILE = "../figures/datasets.tex"
N_GENES = 1000

# Per-dataset facts that cannot be read off the refined h5ad.
#   cite       bibtex key in manuscript/v1/library.bib for the Source column,
#              the paper named in ../data/<Name>_dataset/README* (PBMC has no
#              README: it is the 10x 68k PBMC release of Zheng et al. 2017;
#              Heart_large's README is only a CELLxGENE URL, the paper is the
#              one in the h5ad's uns["citation"]). "" would leave an empty
#              \cite{} placeholder
#   donor_col  obs column whose distinct values are the donors. None with
#              n_donors gives the count directly: PBMC carries no donor
#              column (10x "Fresh 68k PBMCs (Donor A)" is one donor loaded
#              on 8 wells)
#   stage      dev (developmental trajectory) or diff (differentiated tissue)
#   chemistry  the 10x Chromium chemistry. Every dataset is 10x, which the
#              caption states once instead of each row repeating it
DATASET_INFO = {
    "PBMC":         dict(cite="Zheng2017", donor_col=None, n_donors=1, stage="diff",
                         chemistry="3$'$ v1"),
    "Heart_large":  dict(cite="Litvinukova_2020_Nature", donor_col="donor_id", stage="diff",
                         chemistry="3$'$ v2/v3"),
    "BMHemato":     dict(cite="Zhang_2024_NatImmunol", donor_col="Donor", stage="dev",
                         chemistry="CITE-seq (RNA only)"),
    "BMMC":         dict(cite="Luecken_2021_NeurIPS", donor_col="DonorID", stage="diff",
                         chemistry="Multiome (GEX only)"),
    # Zebrahub is a single-embryo atlas: obs["fish"] is the individual
    # embryo or larva, the closest thing to a donor
    "Zebrafish":    dict(cite="Lange_2024_Cell", donor_col="fish", stage="dev",
                         chemistry="3$'$"),
    "Thymus":       dict(cite="Park_2020_Science", donor_col="donor", stage="dev",
                         chemistry="3$'$ and 5$'$"),
    "Breast":       dict(cite="Reed_2024_NatGenet", donor_col="donor_id", stage="diff",
                         chemistry="3$'$ v3"),
    # single-donor extracts added 2026-09-07; see ../data/<Name>_dataset/README.md
    "Fat":          dict(cite="tabulasapiens", donor_col="donor_id", stage="diff",
                         chemistry="3$'$ v3"),
    "Skin":         dict(cite="Reynolds_2021_Science", donor_col="donor_id", stage="diff",
                         chemistry="3$'$ v2"),
    "Ocular":       dict(cite="Jian_2026_openRxiv", donor_col="donor_id", stage="diff",
                         chemistry="3$'$ v3"),
    "Breast_small": dict(cite="Reed_2024_NatGenet", donor_col="donor_id", stage="diff",
                         chemistry="3$'$ v3"),
}

COLUMNS = ["Dataset", "Source", "Donors", "Cells", "Cell types", "Metacells",
           "PCA", "Stage", "Technology"]

HEADER_COMMENT = """\
% GENERATED by python_CITEseq/table.py -- do not edit by hand; rerun
%     python3 table.py
% from python_CITEseq after any rebuild instead.
% Rows are datasets.DEFAULT_DATASETS. Donors, cells, cell types and
% metacells are read from the refined 1000-gene HVG h5ads in
% analysis_HVG_refined/ (donors = distinct values of the dataset's donor
% column, see table.DATASET_INFO); PCA is k, the number of outlier
% eigenvalues predicted by the RMT analysis, i.e. len(pca_theory["values"])
% in the refined 1000-gene spike pkls under analysis_spike_refined/. Source,
% stage and technology come from table.DATASET_INFO.
% Requires \\usepackage{booktabs}."""

CAPTION = r"""  \caption{Single-cell RNA-seq datasets used in this study. All datasets
    were generated on the 10x Chromium platform; Technology gives the
    chemistry. Donors is the number of individuals contributing cells (for
    Zebrafish, the number of individual embryos and larvae). Cell, cell-type
    and metacell counts refer to the refined 1000-gene highly variable gene
    (HVG) files after quality-control filtering and metacell refinement.
    PCA is the dimension $k$ of the PCA space, the number of outlier
    eigenvalues predicted by the RMT analysis for the 1000-gene count
    matrix. Stage is dev (developmental) or diff (differentiated).}"""


def dataset_row(dataset, n_genes=N_GENES):
    """The numbers of one table row, read from the dataset's refined h5ad
    (obs only; X stays on disk) and its refined spike pkl."""
    info = DATASET_INFO[dataset]
    h5ad = dr.refined_filename(dataset, n_genes)
    pca_f = asp.get_pca_filename(dataset, n_genes, refined=True)
    for f in (h5ad, pca_f):
        if not os.path.isfile(f):
            raise FileNotFoundError(f"{f} not found; run make.make_all() first")

    s = ad.read_h5ad(h5ad, backed="r")
    obs = s.obs
    if info["donor_col"] is None:
        n_donors = info["n_donors"]
    elif info["donor_col"] in obs:
        n_donors = obs[info["donor_col"]].nunique()
    else:
        raise KeyError(f"{dataset}: donor column {info['donor_col']!r} not in obs")
    row = {"Dataset": dataset, "Donors": int(n_donors), "Cells": int(s.n_obs),
           "Cell types": int(obs["cell_type"].nunique()),
           "Metacells": int(obs["metacell"].nunique())}
    s.file.close()

    with open(pca_f, "rb") as f:
        row["PCA"] = len(pickle.load(f)["values"])
    row["Source"] = info["cite"]
    row["Stage"] = info["stage"]
    row["Technology"] = info["chemistry"]
    return row


def tex_row(row):
    name = fu.display_name(row["Dataset"]).replace("_", r"\_")
    cells = [f"{name:<14}", f"\\cite{{{row['Source']}}}", str(row["Donors"]),
             f"{row['Cells']:,}", str(row["Cell types"]), str(row["Metacells"]),
             str(row["PCA"]), row["Stage"], row["Technology"]]
    return "    " + " & ".join(cells) + r" \\"


def write_table(table, filename=TABLE_FILE):
    """Write the booktabs table for the rows of `table` (a DataFrame with
    COLUMNS). \\footnotesize and a 5pt \\tabcolsep are what let nine columns
    fit the manuscript's 6.5in text width; at \\small it overflows."""
    lines = [HEADER_COMMENT,
             r"\begin{table}[htbp]",
             r"  \centering",
             r"  \footnotesize",
             r"  \setlength{\tabcolsep}{5pt}",
             r"  \begin{tabular}{llrrrrrll}",
             r"    \toprule",
             "    " + " & ".join(COLUMNS) + r" \\",
             r"    \midrule"]
    lines += [tex_row(row) for _, row in table.iterrows()]
    lines += [r"    \bottomrule",
              r"  \end{tabular}",
              CAPTION,
              r"  \label{tab:datasets}",
              r"\end{table}",
              ""]
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        f.write("\n".join(lines))


def make_datasets_table(dataset_list=None, n_genes=N_GENES, filename=TABLE_FILE):
    """Build the table for `dataset_list` (default datasets.DEFAULT_DATASETS),
    write it to `filename` and return it as a DataFrame."""
    if dataset_list is None:
        dataset_list = datasets.DEFAULT_DATASETS
    missing = [d for d in dataset_list if d not in DATASET_INFO]
    if missing:
        raise KeyError(f"add {missing} to table.DATASET_INFO before building the table")
    table = pd.DataFrame([dataset_row(d, n_genes) for d in dataset_list],
                         columns=COLUMNS)
    write_table(table, filename)
    print(f"wrote {filename} ({len(table)} rows)")
    return table


## knn relative-error table


KNN_TABLE_FILE = "../figures/knn_table.tex"
KNN_K_NN = 10
# (column header, method key in figures_util / analysis_knn), in column
# order. The headers follow the manuscript's \\normal, \\nb, \\perm and \\true
# subscripts, which name the nb-sampled count matrix "metacell".
KNN_COLUMNS = [("Normal", "normal"), ("Metacell", "nb"),
               ("Permuted", "perm"), ("True", "true")]
# the dataset-description columns between Dataset and the errors, as
# (header, dataset_row key, tabular alignment), copied from the datasets
# table's row: Cells, Donors and Cell types are its columns of the same
# name, Type its Stage
KNN_INFO_COLUMNS = [("Cells", "Cells", "r"), ("Donors", "Donors", "r"),
                    ("Cell types", "Cell types", "r"), ("Type", "Stage", "l")]
# rows are sorted ascending on this column's method
KNN_SORT_METHOD = "true"
# the Normal entry is the MEAN of the error over this many replicate draws of
# Z_normal, followed by "[min, max]" over the same draws
# (figures_util.compute_knn_replicate_errors); the single Z_normal draw held
# in the spike pkl is not used for the table
KNN_REPLICATES = 20

KNN_HEADER_COMMENT = """\
% GENERATED by python_CITEseq/table.py -- do not edit by hand; rerun
%     python3 table.py
% from python_CITEseq after any rebuild instead.
% One row per dataset in datasets.DEFAULT_DATASETS that has a refined
% 1000-gene knn pkl under analysis_knn_refined/, sorted by the True column.
% Cells, Donors, Cell types and Type (= Stage) are the datasets
% table's values for the dataset (table.dataset_row). Each error entry is
% figures_util.knn_relative_error for that dataset and count
% matrix: the median over metacell pairs (analytic fraction > 0) of
% |y - x| / |x|, x the LML-RMT predicted k-NN edge fraction and y the
% fraction in the PCA embedding of the count matrix -- the per-dataset
% values whose mean figures.make_knn_figure annotates as REL ERR -- except
% the Normal entry, which is the mean of that error over table.KNN_REPLICATES
% fresh draws of Z_normal, each taken through the SVD and k-NN steps and
% scored against the analytic embedding, followed by [min, max] over the
% same draws (figures_util.compute_knn_replicate_errors, cached as
% <dataset>_HVG_1000_replicates.pkl beside the knn pkls). The knn figure's
% normal panel instead shows the single Z_normal draw held in the spike pkl.
% Requires \\usepackage{booktabs}."""

KNN_CAPTION = r"""  \caption{Relative error of the LML-RMT predictions of the k-nearest
    neighbor graph across metacells (Figure~\ref{F:knn}), by dataset. Cells
    is the number of cells, Donors the number of donors, Cell types the
    number of annotated cell types and Type dev (developmental) or diff
    (differentiated), as in Table~\ref{tab:datasets}.
    For each dataset and count matrix the error entry is the median over ordered
    metacell pairs of $|y - x| / |x|$, where $x$ is the LML-RMT predicted
    fraction of edges from one metacell to the other and $y$ is the
    fraction in the PCA embedding of that count matrix; pairs with a
    predicted fraction of zero are excluded. The normal entry is the mean
    of this error over __NREP__ replicate draws of $Z_\normal$, each taken
    through the PCA and k-nearest neighbor steps in the same way, and the
    range in brackets is the smallest and largest value over those draws;
    it is the spread of the normal error when the model is exact. Rows are
    ordered by the error for the true count matrix, smallest first.}"""


def knn_error_row(dataset, n_genes_list=(N_GENES,), k_nn=KNN_K_NN):
    """One table row: the dataset's cells, donors and type (from
    dataset_row), its relative error under each count matrix, NaN for a
    method its knn pkl lacks, and the min and max replicate error ("Normal
    min" / "Normal max"); None if the dataset has no readable refined knn
    pkl at all. The "Normal" entry is the mean over the replicates rather
    than the spike pkl's single draw, which is left in place under
    "Normal (pkl)" for reference."""
    pairs = fu.compute_knn_edge_fraction_pairs(dataset, n_genes_list, k_nn=k_nn,
                                               refined=True)
    if not pairs:
        return None
    info = dataset_row(dataset, N_GENES)
    row = {"Dataset": dataset}
    for header, source, _ in KNN_INFO_COLUMNS:
        row[header] = info[source]
    for header, method in KNN_COLUMNS:
        row[header] = (fu.knn_relative_error(*pairs[method]) if method in pairs
                       else np.nan)
    replicates = fu.compute_knn_replicate_errors(dataset, N_GENES, n_rep=KNN_REPLICATES,
                                                 k_nn=k_nn, refined=True)
    row["Normal (pkl)"] = row["Normal"]
    if replicates is not None:
        row["Normal"] = replicates.mean()
    row["Normal min"] = np.nan if replicates is None else replicates.min()
    row["Normal max"] = np.nan if replicates is None else replicates.max()
    return row


def knn_columns():
    """The DataFrame columns: Dataset, the info columns, then the error
    columns with the replicate range right after Normal."""
    columns = ["Dataset"] + [h for h, _, _ in KNN_INFO_COLUMNS]
    for header, _ in KNN_COLUMNS:
        columns.append(header)
        if header == "Normal":
            columns += ["Normal min", "Normal max", "Normal (pkl)"]
    return columns


def knn_tex_row(row):
    name = fu.display_name(row["Dataset"]).replace("_", r"\_")
    cells = [f"{name:<14}"]
    for header, _, _ in KNN_INFO_COLUMNS:
        value = row[header]
        cells.append(f"{value:,}" if isinstance(value, (int, np.integer)) else str(value))
    for header, _ in KNN_COLUMNS:
        cell = "--" if np.isnan(row[header]) else f"{row[header]:.2f}"
        if header == "Normal" and not np.isnan(row["Normal min"]):
            cell += f" [{row['Normal min']:.2f}, {row['Normal max']:.2f}]"
        cells.append(cell)
    return "    " + " & ".join(cells) + r" \\"


def write_knn_table(table, filename=KNN_TABLE_FILE):
    """Write the booktabs table for the rows of `table` (a DataFrame with
    knn_columns()), in the order given. The replicate range is folded into
    the Normal cell rather than given columns of its own. \\footnotesize and
    a 5pt \\tabcolsep, as in write_table, are what let the nine columns fit
    the manuscript's 6.5in text width; at \\small it overflows by 30pt."""
    headers = (["Dataset"] + [h for h, _, _ in KNN_INFO_COLUMNS]
               + [h for h, _ in KNN_COLUMNS])
    alignment = "l" + "".join(a for _, _, a in KNN_INFO_COLUMNS) + "r" * len(KNN_COLUMNS)
    lines = [KNN_HEADER_COMMENT,
             r"\begin{table}[htbp]",
             r"  \centering",
             r"  \footnotesize",
             r"  \setlength{\tabcolsep}{5pt}",
             r"  \begin{tabular}{" + alignment + "}",
             r"    \toprule",
             "    " + " & ".join(headers) + r" \\",
             r"    \midrule"]
    lines += [knn_tex_row(row) for _, row in table.iterrows()]
    lines += [r"    \bottomrule",
              r"  \end{tabular}",
              KNN_CAPTION.replace("__NREP__", str(KNN_REPLICATES)),
              r"  \label{tab:knn}",
              r"\end{table}",
              ""]
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        f.write("\n".join(lines))


def make_knn_table(dataset_list=None, n_genes_list=(N_GENES,), k_nn=KNN_K_NN,
                   filename=KNN_TABLE_FILE):
    """Build the knn relative-error table for `dataset_list` (default
    datasets.DEFAULT_DATASETS), one row per dataset with a refined knn pkl,
    sorted ascending on the KNN_SORT_METHOD column; write it to `filename`
    and return it as a DataFrame.

    Reads the same cached knn pkls as figures.make_knn_figure through
    figures_util.compute_knn_edge_fraction_pairs, so the column means are
    that figure's REL ERR values.
    """
    if dataset_list is None:
        dataset_list = datasets.DEFAULT_DATASETS
    rows = [row for row in (knn_error_row(d, n_genes_list, k_nn) for d in dataset_list)
            if row is not None]
    if not rows:
        raise ValueError("no refined knn pkls found; run make.make_downstream first")
    sort_column = dict((m, h) for h, m in KNN_COLUMNS)[KNN_SORT_METHOD]
    table = (pd.DataFrame(rows, columns=knn_columns())
             .sort_values(sort_column, kind="stable", na_position="last")
             .reset_index(drop=True))
    write_knn_table(table, filename)
    print(f"wrote {filename} ({len(table)} rows)")
    return table


## dataset processing table


PROCESSING_TABLE_FILE = "../figures/processing_table.tex"

# The dataset_*.py module whose MIN_/MAX_ threshold constants are the QC
# cutoffs of each dataset (see qc_cutoffs_text). PBMC and Heart_large apply
# their cuts inline rather than through such constants, so their cutoffs are
# written out in PROCESSING_INFO["qc"] instead.
QC_MODULES = {
    "BMHemato": dataset_BMhemato, "BMMC": dataset_BMMC, "Zebrafish": dataset_Zebrafish,
    "Thymus": dataset_thymus, "Breast": dataset_Breast, "Breast_small": dataset_Breast_small,
    "Fat": dataset_Fat, "Skin": dataset_Skin, "Ocular": dataset_Ocular,
}

def cxgid(identifier):
    """A CELLxGENE identifier in typewriter type that may break after any
    hyphen, since typewriter fonts do not break at hyphens on their own."""
    return r"\texttt{" + identifier.replace("-", r"-\allowbreak ") + "}"


# Per-dataset provenance that is not in the code: the identifier of the
# downloaded object (CELLxGENE dataset id, or the repository accession) and
# the cell selection applied before QC. Taken from ../data/<Name>_dataset/
# README* and the dataset_*.py docstrings; edit here, not in the tex file.
#   source  LaTeX text for the Source column
#   pre_qc  LaTeX text for the cell selection before QC
#   qc      LaTeX text for the QC column, only for datasets absent from
#           QC_MODULES
PROCESSING_INFO = {
    "PBMC": dict(
        source="10x Genomics Fresh 68k PBMCs (Donor A), Zheng et al.\\ 2017",
        pre_qc="None; all 68,579 cells.",
        qc="MT $< 5\\%$; UMIs 1,000--3,000; genes with $> 50$ counts."),
    "Heart_large": dict(
        source="CELLxGENE " + cxgid("49312f8c-a75a-4672-9c8a-9078acd35bdb")
               + " (Cells of the adult human heart)",
        pre_qc="Single-cell libraries only: cells with \\texttt{cell\\_source} = Sanger-Cells "
               "(45,885 of 486,134); nuclei and CD45$^+$-enriched libraries excluded.",
        qc="Authors' QC only; genes with $> 50$ counts."),
    "BMHemato": dict(
        source="GEO GSE245108",
        pre_qc="RNA counts of the 71,994 annotated cells in the 12 GEO filtered "
               "matrices; ADT features dropped."),
    "BMMC": dict(
        source="GEO GSE194122 (NeurIPS 2021 multiome BMMC)",
        pre_qc="Batch s1d1 only, GEX features only; cells with $\\ge 100$ genes and "
               "genes in $\\ge 100$ cells (6,224 cells)."),
    "Zebrafish": dict(
        source="Zebrahub, figshare DOI 10.6084/\\allowbreak m9.figshare.\\allowbreak 20510367",
        pre_qc="None; all 120,444 cells (bud stage to 10 dpf)."),
    "Thymus": dict(
        source="Zenodo DOI 10.5281/\\allowbreak zenodo.3572421 (Park et al.\\ 2020)",
        pre_qc="The 76,994 cells of the authors' annotated T cell/thymocyte subset, "
               "with raw counts taken from the full-atlas count matrix."),
    "Breast": dict(
        source="CELLxGENE " + cxgid("2df9adc8-fefc-4a96-9d80-0a7c6b4576e1") + " (HBCA global)",
        pre_qc="None; after QC, 200,000 of the 782,667 passing cells drawn at random."),
    "Fat": dict(
        source="CELLxGENE " + cxgid("5e5e7a2f-8f1c-42ac-90dc-b4f80f38e84c") + " (Tabula Sapiens, fat)",
        pre_qc="Donor TSP25 only, brown adipose tissue libraries only (6 lanes, 40,619 cells)."),
    "Skin": dict(
        source="CELLxGENE " + cxgid("f0f0d7c4-3bec-428e-9539-c99d36548d96") + " (Reynolds et al.\\ 2021)",
        pre_qc="Donor S4 only (50,492 cells)."),
    "Ocular": dict(
        source="CELLxGENE " + cxgid("8560f809-5794-484e-9152-b63efa91d134")
               + " (ocular anterior segment, scRNA-seq)",
        pre_qc="Donor BCM\\_23\\_0131 only (42,612 cells)."),
    "Breast_small": dict(
        source="CELLxGENE " + cxgid("2df9adc8-fefc-4a96-9d80-0a7c6b4576e1") + " (HBCA global)",
        pre_qc="Donor HBCA\\_Donor\\_33 only (39,446 cells); no downsampling."),
}

PROCESSING_COLUMNS = ["Dataset", "Source", "QC cutoffs", "Cell selection before QC"]

PROCESSING_HEADER_COMMENT = """\
% GENERATED by python_CITEseq/table.py -- do not edit by hand; rerun
%     python3 table.py
% from python_CITEseq instead.
% Rows are datasets.DEFAULT_DATASETS. QC cutoffs are read from each
% dataset_*.py module's MIN_/MAX_ constants (table.QC_MODULES; PBMC and
% Heart_large, shown as Heart, are written out in table.PROCESSING_INFO).
% Source and the
% pre-QC cell selection come from table.PROCESSING_INFO, which summarizes
% ../data/<Name>_dataset/README* and the module docstrings.
% Requires \\usepackage{booktabs} and \\usepackage{array}."""

PROCESSING_CAPTION = r"""  \caption{Data sources and cell filtering. Source is the CELLxGENE
    dataset identifier or the repository accession of the downloaded
    counts (for Heart, the dataset version identifier recorded in
    the file). QC cutoffs are the thresholds applied to the raw counts:
    the range of total UMI counts and of genes detected per cell, the
    maximum percentage of mitochondrial (MT) reads, and the gene filter.
    The last column describes any selection of cells made before those
    cutoffs were applied.}"""


def qc_cutoffs_text(dataset):
    """The QC column for one dataset: its module's cell thresholds and gene
    filter, or the hand-written text for datasets without such a module."""
    info = PROCESSING_INFO[dataset]
    if dataset not in QC_MODULES:
        return info["qc"]
    m = QC_MODULES[dataset]
    text = (f"UMIs {m.MIN_TOTAL_COUNTS:,}--{m.MAX_TOTAL_COUNTS:,}; "
            f"genes {m.MIN_GENES_BY_COUNTS:,}--{m.MAX_GENES_BY_COUNTS:,}; "
            f"MT $\\le {m.MAX_PCT_COUNTS_MT}\\%$; ")
    if hasattr(m, "MIN_CELLS_PER_GENE"):
        text += f"genes detected in $\\ge {m.MIN_CELLS_PER_GENE}$ cells."
    else:
        text += f"genes with $\\ge {m.MIN_GENE_COUNTS}$ counts."
    return text


def processing_row(dataset):
    info = PROCESSING_INFO[dataset]
    return {"Dataset": dataset, "Source": info["source"],
            "QC cutoffs": qc_cutoffs_text(dataset),
            "Cell selection before QC": info["pre_qc"]}


def processing_tex_row(row):
    name = fu.display_name(row["Dataset"]).replace("_", r"\_")
    cells = [name, row["Source"], row["QC cutoffs"], row["Cell selection before QC"]]
    return "    " + " & ".join(cells) + r" \\"


def write_processing_table(table, filename=PROCESSING_TABLE_FILE):
    """Write the booktabs table for the rows of `table` (a DataFrame with
    PROCESSING_COLUMNS). Three ragged-right paragraph columns (array's
    \\arraybackslash keeps \\\\ usable inside them) at \\footnotesize; the
    widths sum with the Dataset column to the manuscript's 6.5in text
    width. \\cxgid is defined locally so the file needs no preamble macro."""
    lines = [PROCESSING_HEADER_COMMENT,
             r"\begin{table}[htbp]",
             r"  \centering",
             r"  \footnotesize",
             r"  \setlength{\tabcolsep}{4pt}",
             r"  \begin{tabular}{l >{\raggedright\arraybackslash}p{3.7cm} "
             r">{\raggedright\arraybackslash}p{4.3cm} >{\raggedright\arraybackslash}p{5.2cm}}",
             r"    \toprule",
             "    " + " & ".join(PROCESSING_COLUMNS) + r" \\",
             r"    \midrule"]
    # a little air between rows, since most cells wrap to several lines
    for i, (_, row) in enumerate(table.iterrows()):
        if i:
            lines.append(r"    \addlinespace[3pt]")
        lines.append(processing_tex_row(row))
    lines += [r"    \bottomrule",
              r"  \end{tabular}",
              PROCESSING_CAPTION,
              r"  \label{tab:processing}",
              r"\end{table}",
              ""]
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        f.write("\n".join(lines))


def make_processing_table(dataset_list=None, filename=PROCESSING_TABLE_FILE):
    """Build the processing table for `dataset_list` (default
    datasets.DEFAULT_DATASETS, in that order), write it to `filename` and
    return it as a DataFrame."""
    if dataset_list is None:
        dataset_list = datasets.DEFAULT_DATASETS
    missing = [d for d in dataset_list if d not in PROCESSING_INFO]
    if missing:
        raise KeyError(f"add {missing} to table.PROCESSING_INFO before building the table")
    table = pd.DataFrame([processing_row(d) for d in dataset_list],
                         columns=PROCESSING_COLUMNS)
    write_processing_table(table, filename)
    print(f"wrote {filename} ({len(table)} rows)")
    return table


if __name__ == "__main__":
    pd.set_option("display.width", 200)
    print(make_datasets_table().to_string(index=False))
    print(make_knn_table().to_string(index=False))
    print(make_processing_table().to_string(index=False))
